---
title: "methodology"
author: "Sum Yee Chong"
format: html
execute:
  echo: false
  warning: false
  message: false
---

## Methodology

```{r}
#| label: data-cleaning

library(readxl)
library(tidyverse)
library(knitr)

retail_names <- read_excel(
  "data/Retail turnover, state by industry subgroup, seasonally adjusted.xlsx",
  sheet = "Data1",
  n_max = 1,
  col_names = FALSE
)

```

```{r}
retail_raw <- read_excel(
  "data/Retail turnover, state by industry subgroup, seasonally adjusted.xlsx",
  sheet = "Data1",
  skip = 10,
  col_names = FALSE
)
```

```{r}
names(retail_raw) <- as.character(retail_names[1, ])
names(retail_raw)[1] <- "Date"
retail_raw <- retail_raw[, !is.na(names(retail_raw))]
```

```{r}
retail_long <- retail_raw |>
  pivot_longer(
    cols = -Date,
    names_to = "series",
    values_to = "turnover"
  )

```

```{r}
retail_clean <- retail_long |>
  separate(
    series,
    into = c("measure", "state", "industry"),
    sep = ";"
  ) |>
  mutate(
    Date = as.Date(Date),
    state = str_trim(state),
    industry = str_trim(industry),
    industry = str_replace(
      industry,
      "Furniture, floor coverings, houseware and textile goods retailing",
      "Furniture and houseware retailing"
    )
  ) |>
  filter(
    Date >= as.Date("2020-01-01"),
    Date <= as.Date("2025-05-01"),
    state != "Total (State)",
    industry != "Total (Industry)",
    !is.na(turnover)
  )
```

```{r}
#| label: tbl-summary
#| tbl-cap: "Top 10 state-industry combinations by average monthly retail turnover, 2020–2025 (AUD millions, seasonally adjusted)"


retail_clean |>
  group_by(state, industry) |>
  summarise(
    average_turnover = round(mean(turnover, na.rm = TRUE), 1),
    .groups = "drop"
  ) |>
  arrange(desc(average_turnover)) |>
  head(10) |>
  kable(
    col.names = c("State", "Industry", "Average Turnover ($M)")
  )
```

```{r}
#| label: fig-trend
#| fig-cap: "Monthly retail turnover across selected industries in Australia, January 2020 to May 2025 (seasonally adjusted, AUD millions)"
#| fig-width: 10
#| fig-height: 4

retail_clean |>
  filter(
    industry %in% c(
      "Supermarket and grocery stores",
      "Cafes, restaurants and takeaway food services",
      "Clothing, footwear and personal accessory retailing"
    )
  ) |>
  group_by(Date, industry) |>
  summarise(
    turnover = sum(turnover),
    .groups = "drop"
  ) |>
  ggplot(aes(x = Date, y = turnover, colour = industry)) +
  geom_line(linewidth = 0.8) +
  facet_wrap(~ industry, scales = "free_y") +
  labs(
    x = "Date",
    y = "Turnover ($ Millions)",
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 8)
  )
```
